### PR TITLE
Cygwin version is used in wimpty release url.Add variable CYGWIN_VERSION

### PR DESCRIPTION
**Pull request by ghost**
It was checked on windows 10 and it works fine.

### CODE REVIEW

**Comment by achekulaev** [comment]
I guess it should be
WINPTY_VERSION="winpty-XXXXXXXX-cygwin-XXXXXXX-ia32"

It makes sense to keep string together so no one ever forgets to change both numbers upon release and check url

**Comment by lmakarov** [comment]
I agree with @achekulaev.

**Comment by lmakarov** [comment]
Though... looking closer at the the code it does not seem to be possible to do it that way. Still need two variables:

> `.../download/$WINPTY_VERSION/winpty-$WINPTY_VERSION-cygwin-$CYGWIN_VERSION-ia32.tar.gz`

**Comment by achekulaev** [comment]
@lmakarov oh jeez. And why they have to do it like that... 
Then yeah. Let's go with 2 vars.

LGTM

**Pull request merged**
