### PR TITLE
Cleanup of installation under windows

### PR DESCRIPTION
**Pull request by willoucom**
Adding alternate install under windows (not using babun)
Using choco to install docker and docker-compose (have cleaned presetup-win.sh)
The new presetup-win.cmd script now check administrator rights and can be used "standalone" for a quick installation

### CODE REVIEW

**Comment by lmakarov** [comment]
We used to install `docker` and `docker-compose` Windows binaries with choco, however that made a dependency on choco projects to be up-to-date and was not very reliable and consistent.
Also, I don't remember if it was possible to specify a particular version.

The current approach is made to be consistent across all platforms:
- we define specific version in the scripts, e.g.
  
  ```
  DOCKER_VERSION=1.9.1
  DOCKER_COMPOSE_VERSION=1.5.2
  ```
- then pull them directly from github

There are other parts of the project where we rely on a Linux(-like) shell and tools (cygwin/Babun) for cross-platform consistency and support reasons.

I'm open to suggestion and PRs for a full PowerShell support on Windows, but that's, obviously, a major undertaking.

**Comment by willoucom** [comment]
Ok i understand your point.
There is a new version using version support so the version of docker client is now consistent with the docker inside the VM

**Comment by achekulaev** [comment]
Hi @willoucom 

Thanks for being involved. So your change makes sense if this project was a completely standalone project. However it's part of a bigger initiative called Drude https://github.com/blinkreaction/drude

Majority of lines you remove in your PR are for the needs of further Drude integration. As well as babun installation that is needed to run other Drude routines smoothly. So this pull request as it is now can not be accepted as it would break Drude integration. 

I guess if you made new alternative scripts (totally new, without altering existing ones) that would exist here for people who only want boot2docker-vagrant sans rest of Drude then in that case it could be accepted and merged with appropriate instructions if @lmakarov thinks it is appropriate. If you ask me it would work better as a fork of this project. 

And if you use Drupal we really encourage you to try Drude.

**Comment by lmakarov** [comment]
@willoucom thanks for your input. I'm going to close this PR as we do want to keep things consistent for supportability reasons and thus will stick and require Babun on Windows (at least for now).

**Pull request closed without merging**
